/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/gunicorn/util.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_common.py", line 443, in wrapper
    ret = self._cache[fun]
          ^^^^^^^^^^^
AttributeError: 'Process' object has no attribute '_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_common.py", line 446, in wrapper
    return fun(self)
           ^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_pslinux.py", line 1687, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_common.py", line 776, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_common.py", line 764, in cat
    with _open(fname) as f:
         ^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_common.py", line 728, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/90870/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_pslinux.py", line 1645, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_pslinux.py", line 1855, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/_pslinux.py", line 1652, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=90870)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/__main__.py", line 39, in main
    args.func(args)
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/cli_parser.py", line 52, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/utils/cli.py", line 108, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 489, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 454, in monitor_gunicorn
    ).start()
      ^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 210, in start
    self._wait_until_true(
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 156, in _wait_until_true
    while not fn():
              ^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 211, in <lambda>
    lambda: self.num_workers_expected == self._get_num_workers_running(),
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/cli/commands/webserver_command.py", line 150, in _get_num_workers_running
    workers = psutil.Process(self.gunicorn_master_proc.pid).children()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=90870)
