[2025-06-17T13:19:59.927+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T17:13:53+00:00 [queued]>
[2025-06-17T13:19:59.984+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T17:13:53+00:00 [queued]>
[2025-06-17T13:19:59.985+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-17T13:19:59.985+0200] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2025-06-17T13:19:59.985+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-17T13:20:00.124+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-16 17:13:53+00:00
[2025-06-17T13:20:00.165+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-16T17:13:53+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpbn_05b9d']
[2025-06-17T13:20:00.170+0200] {standard_task_runner.py:83} INFO - Job 32: Subtask pyspark_train_classifier_model
[2025-06-17T13:20:00.167+0200] {standard_task_runner.py:55} INFO - Started process 91354 to run task
[2025-06-17T13:20:00.433+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T17:13:53+00:00 [running]> on host l019.lab.dit.upm.es
[2025-06-17T13:20:00.653+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-16T17:13:53+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-16T17:13:53+00:00
[2025-06-17T13:20:00.655+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-17T13:20:00.655+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa']
[2025-06-17T13:20:00.691+0200] {subprocess.py:86} INFO - Output:
[2025-06-17T13:20:07.071+0200] {subprocess.py:93} INFO - 25/06/17 13:20:07 WARN Utils: Your hostname, l019 resolves to a loopback address: 127.0.1.1; using 138.4.31.19 instead (on interface enp1s0)
[2025-06-17T13:20:07.074+0200] {subprocess.py:93} INFO - 25/06/17 13:20:07 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-17T13:20:14.986+0200] {subprocess.py:93} INFO - 25/06/17 13:20:14 INFO SparkContext: Running Spark version 3.5.3
[2025-06-17T13:20:14.987+0200] {subprocess.py:93} INFO - 25/06/17 13:20:14 INFO SparkContext: OS info Linux, 6.1.0-32-amd64, amd64
[2025-06-17T13:20:14.987+0200] {subprocess.py:93} INFO - 25/06/17 13:20:14 INFO SparkContext: Java version 17.0.14
[2025-06-17T13:20:15.249+0200] {subprocess.py:93} INFO - 25/06/17 13:20:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-17T13:20:15.463+0200] {local_task_job.py:272} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-06-17T13:20:15.524+0200] {process_utils.py:129} INFO - Sending 15 to group 91354. PIDs of all processes in the group: [91357, 91522, 91354]
[2025-06-17T13:20:15.524+0200] {process_utils.py:84} INFO - Sending the signal 15 to group 91354
[2025-06-17T13:20:15.524+0200] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-17T13:20:15.524+0200] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-17T13:20:15.560+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 187, in execute
    result = self.subprocess_hook.run_command(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 1481, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-06-17T13:20:15.576+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=91522, status='terminated', started='13:20:07') (91522) terminated with exit code None
[2025-06-17T13:20:15.582+0200] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250616T171353, start_date=20250617T111959, end_date=20250617T112015
[2025-06-17T13:20:15.672+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 32 for task pyspark_train_classifier_model (Task received SIGTERM signal; 91354)
[2025-06-17T13:20:15.718+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=91354, status='terminated', exitcode=1, started='13:19:59') (91354) terminated with exit code 1
[2025-06-17T13:20:15.811+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=91357, status='terminated', started='13:20:00') (91357) terminated with exit code None
